const view=document.querySelector('#view'),place=document.querySelector('#place'),time=document.querySelector('#time'),status=document.querySelector('#status'),truth=document.querySelector('#truth'),source=document.querySelector('#source'),next=document.querySelector('#next'),seekForm=document.querySelector('#seekForm'),seekInput=document.querySelector('#seekInput'),seekMeta=document.querySelector('#seekMeta');let current=-1,ranked=null;
function local(c){try{return new Intl.DateTimeFormat('en-US',{timeZone:c.tz,weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false,timeZoneName:'short'}).format(new Date())}catch{return''}}
function km(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,dp=r(c-a),dl=r(d-b),q=Math.sin(dp/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function show(c){view.innerHTML='';let el;if(c.type==='iframe'){el=document.createElement('iframe');el.src=c.embed;el.allow='autoplay; encrypted-media; picture-in-picture; fullscreen';el.allowFullscreen=true}else if(c.type==='video'){el=document.createElement('video');el.src=c.embed;el.autoplay=true;el.muted=true;el.playsInline=true;el.controls=true}else{el=document.createElement('img');el.src=c.embed;el.alt=c.place}view.appendChild(el);place.textContent=c.place.toUpperCase();status.textContent=c.status;truth.textContent=c.status+' · '+c.provider.toUpperCase();source.textContent='OPEN SOURCE ↗';source.href=c.source;time.textContent=local(c)}
function fallback(){place.textContent='EARTH';status.textContent='AWAITING VERIFIED LIVE VIEWS';truth.textContent='NO UNVERIFIED CAMERA WILL BE SHOWN';source.textContent='';source.removeAttribute('href')}
function pool(){return ranked||window.WINDOW_CAMERAS||[]}
function somewhere(){const a=pool();if(!a.length)return fallback();let n=Math.floor(Math.random()*a.length);if(a.length>1&&n===current)n=(n+1)%a.length;current=n;show(a[n])}
function coords(q){const m=q.trim().match(/^(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)$/);if(!m)return null;const lat=+m[1],lng=+m[2];return Math.abs(lat)<=90&&Math.abs(lng)<=180?{lat,lng,label:q.trim()}:null}
async function geocode(q){const direct=coords(q);if(direct)return direct;const u='https://geocoding-api.open-meteo.com/v1/search?count=1&language=en&format=json&name='+encodeURIComponent(q);const r=await fetch(u);if(!r.ok)throw Error('geocoder');const j=await r.json(),x=j.results&&j.results[0];if(!x)throw Error('not-found');return{lat:x.latitude,lng:x.longitude,label:[x.name,x.admin1,x.country].filter(Boolean).join(', ')}}
function bestView(c,p){const distanceKm=km(p.lat,p.lng,c.lat,c.lng),distance=55/(1+distanceKm/25),status=c.status==='LIVE'?18:c.status==='NEAR-LIVE'?10:0,media=c.type==='video'?12:c.type==='iframe'?10:5,fresh=Number.isFinite(c.freshnessSeconds)?Math.max(0,10-Math.log10(1+c.freshnessSeconds)*3):0;let direction=0,directionKnown=false;if(Number.isFinite(c.heading)){directionKnown=true;const r=Math.PI/180,y=Math.sin((p.lng-c.lng)*r)*Math.cos(p.lat*r),x=Math.cos(c.lat*r)*Math.sin(p.lat*r)-Math.sin(c.lat*r)*Math.cos(p.lat*r)*Math.cos((p.lng-c.lng)*r),bearing=(Math.atan2(y,x)/r+360)%360,diff=Math.abs(((bearing-c.heading+540)%360)-180);direction=10*Math.max(0,1-diff/90)}return{...c,distanceKm,bestViewScore:Math.round((distance+status+media+fresh+direction)*10)/10,scoreEvidence:{distance:Math.round(distance*10)/10,status,media,freshness:Math.round(fresh*10)/10,direction:Math.round(direction*10)/10,directionKnown}}}
async function seek(q){seekMeta.textContent='SEARCHING PUBLIC VIEWS…';try{const p=await geocode(q),discovered=window.WINDOW_ADAPTERS?await window.WINDOW_ADAPTERS.search(p):(window.WINDOW_CAMERAS||[]),cams=discovered.filter(c=>Number.isFinite(c.lat)&&Number.isFinite(c.lng));ranked=cams.map(c=>bestView(c,p)).sort((a,b)=>b.bestViewScore-a.bestViewScore||a.distanceKm-b.distanceKm);current=0;if(!ranked.length)throw Error('empty');show(ranked[0]);const d=ranked[0].distanceKm<10?ranked[0].distanceKm.toFixed(1):Math.round(ranked[0].distanceKm);seekMeta.textContent=p.label.toUpperCase()+' · BEST VIEW '+d+' KM AWAY · SCORE '+ranked[0].bestViewScore+' · '+ranked.length+' CANDIDATE'+(ranked.length===1?'':'S')}catch(e){seekMeta.textContent=e.message==='not-found'?'LOCATION NOT FOUND':'SEEK UNAVAILABLE · TRY LAT, LNG'}}
seekForm.addEventListener('submit',e=>{e.preventDefault();const q=seekInput.value.trim();if(q)seek(q)});
next.onclick=somewhere;setInterval(()=>{const a=pool();if(current>=0&&a[current])time.textContent=local(a[current])},30000);somewhere();