// Verified-source registry. YouTube live IDs are from the providers' official channels/pages.
// Availability can vary by provider schedule; WINDOW labels scheduled feeds NEAR-LIVE rather than claiming 24/7.
window.WINDOW_CAMERAS=[
 {type:"iframe",place:"Monterey Bay, California",tz:"America/Los_Angeles",status:"NEAR-LIVE",provider:"Monterey Bay Aquarium",embed:"https://www.youtube-nocookie.com/embed/fuCeRkeDxtQ?autoplay=1&mute=1&controls=1&playsinline=1",source:"https://www.montereybayaquarium.org/cams-videos/live-cams/monterey-bay-cam"},
 {type:"iframe",place:"Open Sea · Monterey, California",tz:"America/Los_Angeles",status:"NEAR-LIVE",provider:"Monterey Bay Aquarium",embed:"https://www.youtube-nocookie.com/embed/nNTVZKz219U?autoplay=1&mute=1&controls=1&playsinline=1",source:"https://www.montereybayaquarium.org/cams-videos/live-cams/open-sea-cam"}
 {type:"iframe",place:"Odaiba, Tokyo, Japan",tz:"Asia/Tokyo",status:"LIVE",provider:"Odaiba Live Camera",embed:"https://www.youtube-nocookie.com/embed/fdkVkWU99DI?autoplay=1&mute=1&controls=1&playsinline=1",source:"https://www.youtube.com/watch?v=fdkVkWU99DI"},
 {type:"iframe",place:"Maui, Hawaiʻi",tz:"Pacific/Honolulu",status:"LIVE",provider:"AlohaLiveCam",embed:"https://www.youtube-nocookie.com/embed/Nwnk_jmAMyk?autoplay=1&mute=1&controls=1&playsinline=1",source:"https://www.youtube.com/watch?v=Nwnk_jmAMyk"},
 {type:"iframe",place:"Þorbjörn · Grindavík, Iceland",tz:"Atlantic/Reykjavik",status:"LIVE",provider:"AfarTV",embed:"https://www.youtube-nocookie.com/embed/bEOPDN710JQ?autoplay=1&mute=1&controls=1&playsinline=1",source:"https://www.youtube.com/watch?v=bEOPDN710JQ"},
 {type:"iframe",place:"Maunakea Summit · Hawaiʻi",tz:"Pacific/Honolulu",status:"LIVE",provider:"Subaru Telescope × Asahi",embed:"https://www.youtube-nocookie.com/embed/Iz0rFcyHf1k?autoplay=1&mute=1&controls=1&playsinline=1",source:"https://subarutelescope.org/en/news/topics/2021/04/21/2946.html"},
 {type:"iframe",place:"Teton Range · Moose, Wyoming",tz:"America/Denver",status:"LIVE",provider:"U.S. National Park Service",embed:"https://www.nps.gov/media/webcam/view.htm?id=9603ED1D-F805-714D-AC4557683B558B00",source:"https://www.nps.gov/grte/learn/photosmultimedia/tetonrangewebcam.htm"},
 {type:"iframe",place:"Dumpling Mountain · Katmai, Alaska",tz:"America/Anchorage",status:"NEAR-LIVE",provider:"U.S. National Park Service",embed:"https://www.nps.gov/media/webcam/view.htm?id=D3544467-9A96-0068-4B745F74BE0F93F8",source:"https://www.nps.gov/katm/learn/photosmultimedia/dumpling-mountain-cam.htm"},
];