// Verified-source registry. Coordinates are approximate camera/site locations used for proximity ranking.
// Availability varies by provider schedule; WINDOW never upgrades a feed's truth label merely because it loads.
window.WINDOW_CAMERAS=[
 {type:"iframe",place:"Monterey Bay, California",lat:36.618,lng:-121.901,tz:"America/Los_Angeles",status:"NEAR-LIVE",provider:"Monterey Bay Aquarium",embed:"https://www.youtube-nocookie.com/embed/fuCeRkeDxtQ?autoplay=1&mute=1&controls=1&playsinline=1",source:"https://www.montereybayaquarium.org/cams-videos/live-cams/monterey-bay-cam"},
 {type:"iframe",place:"Open Sea · Monterey, California",lat:36.618,lng:-121.901,tz:"America/Los_Angeles",status:"NEAR-LIVE",provider:"Monterey Bay Aquarium",embed:"https://www.youtube-nocookie.com/embed/nNTVZKz219U?autoplay=1&mute=1&controls=1&playsinline=1",source:"https://www.montereybayaquarium.org/cams-videos/live-cams/open-sea-cam"},
 {type:"iframe",place:"Odaiba, Tokyo, Japan",lat:35.627,lng:139.776,tz:"Asia/Tokyo",status:"LIVE",provider:"Odaiba Live Camera",embed:"https://www.youtube-nocookie.com/embed/fdkVkWU99DI?autoplay=1&mute=1&controls=1&playsinline=1",source:"https://www.youtube.com/watch?v=fdkVkWU99DI"},
 {type:"iframe",place:"Maui, Hawaiʻi",lat:20.798,lng:-156.332,tz:"Pacific/Honolulu",status:"LIVE",provider:"AlohaLiveCam",embed:"https://www.youtube-nocookie.com/embed/Nwnk_jmAMyk?autoplay=1&mute=1&controls=1&playsinline=1",source:"https://www.youtube.com/watch?v=Nwnk_jmAMyk"},
 {type:"iframe",place:"Þorbjörn · Grindavík, Iceland",lat:63.86,lng:-22.44,tz:"Atlantic/Reykjavik",status:"LIVE",provider:"AfarTV",embed:"https://www.youtube-nocookie.com/embed/bEOPDN710JQ?autoplay=1&mute=1&controls=1&playsinline=1",source:"https://www.youtube.com/watch?v=bEOPDN710JQ"},
 {type:"iframe",place:"Maunakea Summit · Hawaiʻi",lat:19.823,lng:-155.469,tz:"Pacific/Honolulu",status:"LIVE",provider:"Subaru Telescope × Asahi",embed:"https://www.youtube-nocookie.com/embed/Iz0rFcyHf1k?autoplay=1&mute=1&controls=1&playsinline=1",source:"https://subarutelescope.org/en/news/topics/2021/04/21/2946.html"},
 {type:"iframe",place:"Teton Range · Moose, Wyoming",lat:43.655,lng:-110.718,tz:"America/Denver",status:"LIVE",provider:"U.S. National Park Service",embed:"https://www.nps.gov/media/webcam/view.htm?id=9603ED1D-F805-714D-AC4557683B558B00",source:"https://www.nps.gov/grte/learn/photosmultimedia/tetonrangewebcam.htm"},
 {type:"iframe",place:"Dumpling Mountain · Katmai, Alaska",lat:58.392,lng:-155.239,tz:"America/Anchorage",status:"NEAR-LIVE",provider:"U.S. National Park Service",embed:"https://www.nps.gov/media/webcam/view.htm?id=D3544467-9A96-0068-4B745F74BE0F93F8",source:"https://www.nps.gov/katm/learn/photosmultimedia/dumpling-mountain-cam.htm"}
];